name: 🚀 Deploy website to FTP on push for new version tags

on:
  push:
    branches:
      - test
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
      - 'v[0-9]+.[0-9]+.[0-9]'
  workflow_run:
    workflows: ["Inject git tags into HTML that will be displaed in the footer"]
    branches: [main]
    types: 
      - completed

jobs:
  web-deploy:
    environment: production
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        server-dir: /ageriq/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          backend/docs/**
          backend/docs/**
          backend/.env
          backend/composer.json
          backend/composer.lock
          backend/Dockerfile
          README.txt
          frontend/Dockerfile
          frontend/nginx.dev.conf
          frontend/public/config.js
          frontend/public/config.sample.js