name: Inject git tags into HTML that will be displaed in the footer

on:
  push:
    branches:
      - test
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current project tag
        id: get_tag
        run: echo "PROJECT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Inject tags into HTML
        run: |
          touch version.html
          sed -i "s/%%PROJECT_TAG%%/${{ env.PROJECT_TAG }}/g" version.html

      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/albrzykowski/wii-frontend.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
