name: Inject git tags into HTML that will be displaed in the footer

on:
  push:
    branches:
        - test
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current project tag
        id: get_tag
        run: echo "PROJECT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Inject tags into HTML
        run: |
          touch version.html
          sed -i "s/%%PROJECT_TAG%%/${{ env.PROJECT_TAG }}/g" version.html
      - name: Save version artifact
        uses: actions/upload-artifact@v4
        with:
            name: version-html
            path: version.html
